### ISSUE TITLE
Linkedin share url has changed

### ISSUE THREAD

**Issue by CecileBr** [WordPressUtilities/WPUTheme#4]
Hi @Darklg,

I was about to implement the Linkedin sharing method and I noticed Linkedin has changed the url.
``` html
// old
https://www.linkedin.com/shareArticle?mini=true&url=URL&summary=&source=

// new
https://www.linkedin.com/sharing/share-offsite/?url=URL
```

The new url only accept `url` as parameter.
Now, if you use the old link, Linkedin automatically converts it to the new one letting only the `url` parameter.

I guess one day they'll deprecate the old url.

Not much official info about it, but here are a few links :
- [https://stackoverflow.com/a/61856180/18965331](https://stackoverflow.com/a/61856180/18965331) 
- [https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin)

I'll be happy to make a PR if you think it will be useful.

**Comment by Darklg** [comment]
Hi @CecileBr !

Great suggestion, i will update this today !

**Comment by Darklg** [comment]
Thank you for the notification of course !

**Comment by Darklg** [comment]
@CecileBr Thank you again, the URL is up-to-date ! I let you close the issue if everything is ok for you.

**Comment by CecileBr** [comment]
Thanks!
